version: '3.9'
 
services:
  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      retries: 5
      start_period: 20s
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=secretpass
    networks:
      - network-backend
    volumes:
      - db_data:/var/lib/postgresql/data
 
  backend:
    build: .
    deploy:
      replicas: 3
    restart: always
    environment:
      - FLASK_DB_HOST db
    expose:
      - 5000
    networks:
      - network-backend
      - network-frontend
    depends_on:
      db:
        condition: service_healthy
 
  frontend:
    build:
      context: frontend
    restart: always
    ports:
      - 3000:80
    networks:
      - network-frontend
      - network-backend
 
networks:
  network-backend:
  network-frontend:
 
volumes:
  db_data: